The Hegemony Manifesto
* Table of Contents
** Avatars
   Avatars are the player-controlled characters in hegemony. 
*** Unlimited
    Players own and control any number of avatars.
    Concievably, avatars can be transferred between players.
*** Permanent Death
    Avatars can be killed.
**** Vulnerability
     Certain actions require that the avatar be exposed to danger

*** Capabilities
**** Asset Control
***** Piloting
      Spacecraft require one or more avatars to operate
***** 
** Populations
   Populations are collections of NPCs; permanent residents.
** Locations
*** Surface
**** Habitable
**** Nonhabitable
*** Space




* Hegemony centers around populations

Populations are the substitute for traditional NPCs. Player characters are drawn from populations, starting at the lowest level with no reputation and relative anonymity.

----

* Worlds are the sum of geographically discrete nodes

Hegemony is played on clestial satellites, represented by spherical maps. The maps are sectioned into population nodes, georgraphically distributed according to the coordinates of a subdivided icosahedron. Each population, therefore, exists on a single node, which is controlled by a zero or one player characters.

Those who play hegemony vie for regional, or even global, dominance by placing characters they control as governors of population nodes. Populations are only interested only in their own state of affairs; they are agnostic to the regional and global ties of their governors.

----

Regional nodes may contain untapped resources, and can store stockpiles of resources, goods, and a standing military. These are owned by the local populace, but their usage is directed by the player-character governor.

Resources, goods, and military units can only move between adjacent nodes, and cannot exceed the storage capacity of a node. Cooperating adjacent governors can trade, while adverse adjacent governors may attempt to invade.

----

Player characters need not be governors, and need not reside in nodes controlled by a governor owned by the same player. All characters, governors included, have the ability to benefit or augment the resources, production, military, and even characteristics of the population. 

These booster effects are gained through event experience, forcing players to develop their characters in strategic ways. Players can use characters to assist governors that they may or may not own. In this way, hegemony becomes a game of connections, and who you know becomes extremely important.

----

Natural Resources

Common ores (think: metals)
Rare minerals (think: silicon)
Fuel (think: oil)
Food

The distribution of natrual resources 

Militaries, industries, and populations themselves have upkeep costs. Insufficient resources imposes hard limits on military size and production, and will make populations less efficient and more difficult to govern. Specialist characters may be required to take advantage of certain classes of resources

----


* Getting back on topic...
  
  The whole governor's idea is a bit restrictive, so i'm going to list some key features i want to see of this game
  
** Passive play
   
   Players own a practically unbounded number of characters. Characters have assets, and assets grant a range 
   abilities and actions.
   
   Players manipulate the game state via a real-time API. The number of connections is unbounded; players can
   manage more characters concurrently to do more things. In this way, players can experience the simulation at
   a strategic level, and can automate different processes. On the other hand, the rate of commands sent by clients
   can be throttled.
   

** Assets

   Distinct concepts of ownership and permissions. Characters can grant/revoke asset usage to other characters.
   
*** Units
    
    Capital ships, fleets, ground platoons. Maybe they require some sort of experience to use effectively, but there
    shouldn't be a grind to acquire skills - rather, new characters with different types of experience can be earned
    from populations.
    
*** Structures
    
    Ground and space. Always vulnerable, but can use a civ-like garrison mechanic.
    
*** Resources

    Stored in structures, everything in industry is built here.



** Populations

   Populations are the source for new characters. The type of civilization, it's health/happiness, and its standings 
   toward the character determine the types of new characters that a player can acquire.

   The simulation here is going to be insane.

*** Ground

    Naturally occuring in the game, planets or moons have large native populations. New players can easily spawn
    a fair number of low-skill characters from planetary populations. Older players can spend more time increasing
    favor to get access to rare specialists.

    Military Nation
    Technologist Utopia
    Slaver World
    Industrial Powerhouse
    Colony
    
*** Space

    Large-scale space stations and asteroid colonies provide highly specialized characters, but generally at a higher
    cost than planetary counterparts.
    
    Mining Outpost
    Aeronautics Academy
    Pirate/Mercenary Base
    
    
** Characters

*** Leadership

    Maybe this breaks the 'unbounded characters' idea, but to control larger numbers of mid- and low-level characters,
    heirarchies of leaders may be needed to unlock 'subordinate slots'

*** Military

    Used to give bonuses for combat, or allow use of certain unit assets.

*** Industrial/Economic
    
    Bonuses to resource gathering and production management, education in requisite techniques and methods
    
*** Political/influential

    Money sinks - passively manipulate influence
    
