The Hegemony Manifesto

* Table of Contents
** Avatars
   Avatars are the player-controlled characters in hegemony. 
*** Unlimited
    Players own and control any number of avatars.
    Concievably, avatars can be transferred between players.
*** Permanent Death
    Avatars can be killed; certain actions require that the avatar be
    exposed to danger
*** Capabilities
**** Warehousing
     Populations provide storage services, subject to rent based on
     standings
**** Manufacturing
     See further discussion.
**** Piloting
     Spacecraft require one or more avatars to operate
**** Troop command
     NPC ground forces can be controlled only by avatars with the
     requisite leadership credentials. 
**** Population interaction
***** Commerce
      Populations have specific needs, and fulfilling them can be
      financially lucrative and will lead to stronger connections.
***** Politics
      Become a member of the permanent population - winning elections
      helps grant control over the local treasury.
***** Avatar spawning
      All avatars are drawn from populations; tighter connections to a
      population allow the generation of more highly specialized avatars.
** Spacecraft
   The key to conquest and trade
*** Travel
    Travel time is non-trivial; thus moving assets is a commitment
    with consequences.
*** Battles
** Ground Units
   Not all battles are won in space
*** Conscription
    Drawn from the population at a initial cost in proportion to
    abilities and experience
*** Upgrades
    Develop finely tuned specialists or versatile commandos at a cost
    of experience points and capital.
*** Battles
    
** Manufacturing
   "Who do you think makes your ammo" -j4g
** Locations
   
   |                  | Lush World   | Barren World | Asteroids | Orbital Stations |
   |------------------+--------------+--------------+-----------+------------------|
   | Population Class | Large        | Medium       | Small     | Small            |
   |                  | sustaintable | depdendent   | dependent | dependent        |
   |------------------+--------------+--------------+-----------+------------------|
   | Resources        | Food/Water   | Fuels        | Minerals  | Specialists      |
   | (by comparative  | Conscription |              |           |                  |
   | advantage)       |              |              |           |                  |
